apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-dev-environment
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: devsecops
    repoURL: https://github.com/Daniel-iyak/DevSecOps.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true